Update SetupVeeamVM

diff --git a/SetupVeeamVM b/SetupVeeamVM
--- a/SetupVeeamVM
+++ b/SetupVeeamVM
@@ -1,10 +1,13 @@
 #!/bin/bash  
+# Set variable defaults
 vupw="NOT SET"
 tapw="NOT SET"
 nasip="NOT SET"
 lturl="NOT SET"
 devnm="/dev/sdb"
 host="NOT SET"
+
+# Function to actually do install
 installfunction () {
   cat<<EOF
   Starting setup using:
@@ -15,165 +18,161 @@ installfunction () {
   - LT URL: $lturl
   - HVHOST: $host
 
-EOF
-echo "Take a checkpoint of the VM now so if something goes wrong you can roll back easily, hit any key when ready ..."
-read -s
-echo "Changing tabadmin password ... this is manual but you wanted to use "$tapw
-sudo passwd -d tabadmin
-passwd
-if [ $? != 0 ]; then
-  echo "Something happened here, gonna quit.";
+  EOF
+  read -ps "Take a checkpoint of the VM now so if something goes wrong you can roll back easily, hit any key when ready ..."
+  echo
+  # Change TABADMIN password
+  echo "Changing tabadmin password ... this is manual but you wanted to use "$tapw
+  sudo passwd -d tabadmin
+  passwd
+  if [ $? != 0 ]; then
+    echo "Something happened here, gonna quit.";
+    exit
+  fi
+  # Check the NAS IP is reachable
+  echo "Checking the NAS IP ..."
+  ping -c 5 $nasip
+  if [ $? != 0 ]; then
+    echo "NAS doesn't answer pings, gonna quit.";
+    exit
+  fi
+  # Update base OS
+  read -sp "Running updates, hit any key to start ..."
+  sudo apt update
+  sudo apt upgrade -y
+  # install apps we want
+  sudo apt install -y bmon unzip default-jre
+  echo
+  echo "Stopping iSCSI services ..."
+  sudo systemctl stop iscsid open-iscsi iscsid.socket
+  echo "Updating Initiator Name ..."
+  sudo cat > /etc/iscsi/initiatorname.iscsi <<EOF
+  InitiatorName=iqn.2004-10.com.$host:veeamxfs01:c6b852bc3730
+  EOF
+  if [ $? != 0 ]; then
+    echo "Rename didn't take, gonna quit.";
+    exit
+  fi
+  read -sp "Take note of the iSCSI ID below then hit any key to continue ..."
+  sudo cat /etc/iscsi/initiatorname.iscsi
+  echo 
+  read -sp "Make sure you configure the NAS now for iSCSI and provide that ID then hit any key to continue... "
+  echo
+  read -sp "Hit any key to open the iSCSI config file. Remove the comment before the automatic start and add one before the manual start..."
+  sudo nano /etc/iscsi/iscsid.conf
+  echo
+  echo "Restarting iSCSI service ..."
+  sudo systemctl restart iscsid open-iscsi iscsid.socket
+  if [ $? != 0 ]; then
+    echo "Service didn't restart normally, gonna quit.";
+    exit
+  fi
+  echo
+  echo "Connecting to iSCSI ..."
+  sudo iscsiadm -m discovery -t sendtargets -p $nasip
+  if [ $? != 0 ]; then
+    echo "Couldn't find any targets, gonna quit.";
+    exit
+  fi
+  echo
+  echo "Logging in to iSCSI ..."
+  sudo iscsiadm -m node --login
+  if [ $? != 0 ]; then
+    echo "Login failed, gonna quit.";
+    exit
+  fi
+  echo
+  echo "Creating volume ..."
+  sudo parted --script $devnm "mklabel gpt"
+  if [ $? != 0 ]; then
+    echo "Partitioning failed, gonna quit.";
+    exit
+  fi
+  sudo parted --script $devnm "mkpart primary 0% 100%"
+  if [ $? != 0 ]; then
+    echo "Partitioning failed, gonna quit.";
+    exit
+  fi
+  echo 
+  echo "Formatting volume ..."
+  sudo mkfs.xfs -b size=4096 -m reflink=1,crc=1 $devnm -f -K
+  if [ $? != 0 ]; then
+    echo "Format failed, gonna quit.";
+    exit
+  fi
+  echo
+  sudo blkid $devnm
+  read -sp "Take note of the UUID above then hit any key to conitnue to edit the fstab file ..."
+  echo "Add this line /dev/disk/by-uuid/--the_UUID_FROM ABOVE--/mnt/veeamrepo xfs _netdev 0 0"
+  read -sp "Hit any key to continue ..."
+  sudo mkdir /mnt/veeamrepo
+  if [ $? != 0 ]; then
+    echo "Couldn't make folder, gonna quit.";
+    exit
+  fi
+  sudo nano /etc/fstab
+  echo
+  echo "Attempting to mount volume ..."
+  sudo mount -a
+  if [ $? != 0 ]; then
+    echo "Mounting failed, gonna quit.";
+    exit
+  fi
+  echo "Listing volumes mapped to " $devnm "..."
+  df -H | grep $devnm
+  echo
+  read -sp "Does this look right? If so hit any key otherwise CTRL+BREAK now and bail ..."
+  echo
+  echo "Creating veeamuser ..."
+  sudo useradd veeamuser --create-home -s /bin/bash
+  if [ $? != 0 ]; then
+    echo "Adding the user failed, gonna quit.";
+    exit
+  fi
+  yes $vupw | sudo passwd veeamuser
+  if [ $? != 0 ]; then
+    echo "Setting the password failed, gonna quit.";
+    exit
+  fi
+  sudo usermod -a -G sudo veeamuser
+  if [ $? != 0 ]; then
+    echo "Making the user a SUDO user failed, gonna quit.";
+    exit
+  fi
+  sudo chown -R veeamuser:veeamuser /mnt/veeamrepo/
+  if [ $? != 0 ]; then
+    echo "Setting permissions failed, gonna quit.";
+    exit
+  fi
+  sudo chmod 700 /mnt/veeamrepo/
+  if [ $? != 0 ]; then
+    echo "Setting permissions failed, gonna quit.";
+    exit
+  fi
+  echo
+  echo "Installing LT agent"
+  wget -O agent.zip $lturl
+  if [ $? != 0 ]; then
+    echo "Getting the LT agent failed, gonna quit.";
+    exit
+  fi
+  unzip agent.zip
+  if [ $? != 0 ]; then
+    echo "Unzipping the agent failed, gonna quit.";
+    exit
+  fi
+  cd LTechAgent/
+  chmod +x install.sh
+  sudo ./install.sh
+  echo "Install done, you can verify in the thick client then press any key to continue ..."
+  read -s
+  echo "Script is mostly done - configure Veeam now and when done return to this window"
+  echo "Hit any key ..."
+  read -s
+  echo "Removing veeamuser from SUDO group"
+  sudo usermod -a -G sudo veeamuser
   exit
-fi
-echo "Checking the NAS IP ..."
-ping -c 5 $nasip
-if [ $? != 0 ]; then
-  echo "NAS doesn't answer pings, gonna quit.";
-  exit
-fi
-echo "Running updates, hit any key to start ..."
-read -s
-sudo apt update
-sudo apt upgrade -y
-sudo apt install -y bmon unzip default-jre
-echo
-echo "Stopping iSCSI services ..."
-sudo systemctl stop iscsid open-iscsi iscsid.socket
-echo "Updating Initiator Name ..."
-sudo cat > /etc/iscsi/initiatorname.iscsi <<EOF
-iqn.2004-10.com.2022-$host:veeamxfs01:c6b852bc3730
-EOF
-if [ $? != 0 ]; then
-  echo "Rename didn't take, gonna quit.";
-  exit
-fiecho "Take note of the iSCSI ID below then hit any key to continue ..."
-read -s
-sudo cat /etc/iscsi/initiatorname.iscsi
-echo
-echo "Make sure you configure the NAS now for iSCSI and provide that ID then hit any key to continue... " 
-read -s
-echo
-echo "Hit any key to open the iSCSI config file. Remove the comment before the automatic start and add one before the manual start..."
-read -s
-sudo nano /etc/iscsi/iscsid.conf
-echo
-echo "Restarting iSCSI service ..."
-sudo systemctl restart iscsid open-iscsi iscsid.socket
-if [ $? != 0 ]; then
-  echo "Service didn't restart normally, gonna quit.";
-  exit
-fi
-echo
-echo "Connecting to iSCSI ..."
-sudo iscsiadm -m discovery -t sendtargets -p $nasip
-if [ $? != 0 ]; then
-  echo "Couldn't find any targets, gonna quit.";
-  exit
-fi
-echo
-echo "Logging in to iSCSI ..."
-sudo iscsiadm -m node --login
-if [ $? != 0 ]; then
-  echo "Login failed, gonna quit.";
-  exit
-fi
-echo
-echo "Creating volume ..."
-sudo parted --script $devnm "mklabel gpt"
-if [ $? != 0 ]; then
-  echo "Partitioning failed, gonna quit.";
-  exit
-fi
-sudo parted --script $devnm "mkpart primary 0% 100%"
-if [ $? != 0 ]; then
-  echo "Partitioning failed, gonna quit.";
-  exit
-fi
-echo 
-echo "Formatting volume ..."
-sudo mkfs.xfs -b size=4096 -m reflink=1,crc=1 $devnm -f -K
-if [ $? != 0 ]; then
-  echo "Format failed, gonna quit.";
-  exit
-fi
-echo
-sudo blkid $devnm
-echo "Take note of the UUID above then hit any key to conitnue to edit the fstab file ..."
-read -s
-echo "Add this line /dev/disk/by-uuid/--the_UUID_FROM ABOVE--/mnt/veeamrepo xfs _netdev 0 0"
-echo "Hit any key to continue ..."
-read -s
-sudo mkdir /mnt/veeamrepo
-if [ $? != 0 ]; then
-  echo "Couldn't make folder, gonna quit.";
-  exit
-fi
-sudo nano /etc/fstab
-echo
-echo "Attempting to mount volume ..."
-sudo mount -a
-if [ $? != 0 ]; then
-  echo "Mounting failed, gonna quit.";
-  exit
-fi
-echo "Listing volumes mapped to " $devnm "..."
-df -H | grep $devnm
-echo
-echo "Does this look right? If so hit any key otherwise CTRL+BREAK now and bail ..."
-read -s
-echo
-echo "Creating veeamuser ..."
-sudo useradd veeamuser --create-home -s /bin/bash
-if [ $? != 0 ]; then
-  echo "Adding the user failed, gonna quit.";
-  exit
-fi
-yes $vupw | sudo passwd veeamuser
-if [ $? != 0 ]; then
-  echo "Setting the password failed, gonna quit.";
-  exit
-fi
-sudo usermod -a -G sudo veeamuser
-if [ $? != 0 ]; then
-  echo "Making the user a SUDO user failed, gonna quit.";
-  exit
-fi
-sudo chown -R veeamuser:veeamuser /mnt/veeamrepo/
-if [ $? != 0 ]; then
-  echo "Setting permissions failed, gonna quit.";
-  exit
-fi
-sudo chmod 700 /mnt/veeamrepo/
-if [ $? != 0 ]; then
-  echo "Setting permissions failed, gonna quit.";
-  exit
-fi
-echo
-echo "Installing LT agent"
-wget -O agent.zip $lturl
-if [ $? != 0 ]; then
-  echo "Getting the LT agent failed, gonna quit.";
-  exit
-fi
-unzip agent.zip
-if [ $? != 0 ]; then
-  echo "Unzipping the agent failed, gonna quit.";
-  exit
-fi
-cd LTechAgent/
-chmod +x install.sh
-sudo ./install.sh
-echo "Install done, you can verify in the thick client then press any key to continue ..."
-read -s
-echo "Script is mostly done - configure Veeam now and when done return to this window"
-echo "Hit any key ..."
-read -s
-echo "Removing veeamuser from SUDO group"
-sudo usermod -a -G sudo veeamuser
-exit
 }
-
-
 
 while :
 do
